version: '3.5' # lower version to work with current ubuntu lts
services:
  mindustry:
    image: ghcr.io/shanefagan/mindustry_server/mindustry_server

    # build:
    #   context: . # build context instead of pulling the image

    # enable tty and stdin to make `docker attach` work
    tty: true
    stdin_open: true

    # trust no one :)
    read_only: true
    cap_drop:
      - ALL

    ports:
      - "6567:6567"
    restart: unless-stopped

    # map config to host machine
    volumes:
      - ./config:/config
