name: Build project

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }} # - must be in GitHub Secrets!

      - name: Set date # to avoid clashing verison names
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build
        run: |
          docker build . --tag ghcr.io/shanefagan/mindustry_server/mindustry_server:${{ steps.date.outputs.date }}
          docker push ghcr.io/shanefagan/mindustry_server/mindustry_server:${{ steps.date.outputs.date }}
