name: Build project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name:
        run: |
          echo $(date +'%Y-%m-%dT%H:%M') >> $GITHUB_ENV
      - name: Build
        run: |
          docker build . --tag $NOW
