name: Build project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set date # to avoid clashing verison names
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build
        run: |
          docker build . --tag mindustry_server:${{ steps.date.outputs.date }}
